FWproject/FWapp/urls.py
from django . urls import path
from . import views

app_name = 'FWapp'
urlpatterns = [
    path('', views.procat, name='procat'),
    path('<slug:catslug>/', views.procat, name='products_by_category'),
    path('<slug:catslug>/<slug:proslug>/', views.prodeta, name='procatdet')
]

FWproject/FWproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('FWapp/',include('FWapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

FWproject/cart/urls.py
from  django.urls import path
from . import views

app_name='cart'

urlpatterns=[
    path('add/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')
]

FWproject/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns = [
    path('', views.Search, name='Search'),
]

FWproject/FWapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('FWapp:products_by_category', args=[self.slug])


class Products(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('FWapp:procatdet',args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

FWproject/cart/models.py
from django.db import models
from FWapp.models import Products


# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class Items(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'Items'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

FWproject/FWapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Products
from django. core . paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.


def procat(request,catslug=None):
    cat = None
    pro_list = None
    if catslug!= None:
        cat = get_object_or_404(Category, slug=catslug)
        pro_list = Products.objects.all().filter(category=cat, available=True)
    else:
        pro_list = Products.objects.all().filter(available=True)
    pagin=Paginator(pro_list,3)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        pro=pagin.page(page)
    except(EmptyPage,InvalidPage):
        pro = pagin.page(pagin.num_pages)

    return render(request, "category.html", {'category': cat, 'products': pro})


def prodeta(request, catslug, proslug):
    try:
        product = Products.objects.get(category__slug=catslug, slug=proslug)
    except Exception as b:
        raise b
    return render(request, 'product.html', {'product': product})

FWproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from FWapp.models import Products
from .models import Cart, Items
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_to_cart(request, product_id):
    product = Products.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=cart_id(request)
        )
        cart.save(),
    try:
        cart_item = Items.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except Items.DoesNotExist:
        cart_item = Items.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
        cart_items = Items.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Products, id=product_id)
    cart_item = Items.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Products, id=product_id)
    cart_item = Items.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

FWproject/search_app/views.py
from django.shortcuts import render
from FWapp. models import Products
from django.db.models import Q
# Create your views here.


def Search(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get("q")
        products=Products.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

FWproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

FWproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
     Place the order
{% endblock %}
{% block title %}
    Cart - Best Choice PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
       <br>
        <h1 class="text-center my_title">
            Your Shopping Cart is empty
        </h1>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'FWapp:procat' %}">Here</a>to continue shopping.
        </p>
    </div>
</div>
{% else %}
<div class="row cart_row_class">
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table custom_table">
            <thead class="custom_thead">
            <tr>
                <th colspan="5">
                    Your Items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
             <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"> <img src="{{cart_item.product.image.url}}" alt="" style="width:100px;height:100px;" class="float-right rounded custom_image"></a>
                </td>
                <td class="text-lef">
                    {{cart_item.product.name}}
                    <br>
                    SKU:{{cart_item.product.id}}
                    <br>
                    Price:$ {{cart_item.product.price}}
                    <br>
                    Qty:{{cart_item.quantity}} x $ {{cart_item}}
                </td>
                <td>
                    ${{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                  <td>
                     <a href="{% url 'cart:add_to_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus-square"></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus-square"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-trash-restore-alt"></i></a>
                  </td>
                {% else %}
                  <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus-square"></i> </a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-trash-restore-alt"></i> </a>
                  </td>
                 {% endif %}
                   </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table custom_table">
            <thead class="custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Review your Cart Items.
                </td>
            </tr>
            <td class="text-left">
                Total:<strong> {{total}}</strong>
            </td>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'FWapp:procat' %}" class="btn btn-secondary btn-block custom_button">Continue Shopping</a>
        </div>
        <br>
         <div class="mx-auto">
            <a href="{% url 'FWapp:procat' %}" class="btn btn-outline-success">Payment</a>
        </div>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

FWproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
       {{category.description|truncatewords:155}}
    {% else %}
       Welcome to Best Choice
    {% endif %}
{% endblock %}

{% block title %}
     {% if category %}
       {{category.name}} - Best Choice Shop
    {% else %}
      Our new collections - Best Choice Shop
    {% endif %}
{% endblock %}
{% block content %}
{% if category %}
   <div>
       <div class="row r_class">
           <div class="mx-auto">
          <p><a href="{% url 'FWapp:procat' %}">Products Collections</a></p>
       </div>
   </div>
   </div>
{% endif %}
   <div class="mx_auto">
       {% if category %}
      <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" height="100px;" width="50px;">
   </div>
<br>
   <div>
      <h1 class="text-center my_title">{{category.name}}</h1>
      <p class="text-justify">{{category.description}}</p>
   </div>
   {% else %}
   <div>
     <img class="my_image image_padding" src="{% static 'image/banner.png' %}" alt="Our products">
   </div>
<br>
    <div>
      <h1 class="text-center my_title">Our products collections</h1>
        <p class="text-justify">This family company believes that trust and loyalty are earned. That's why when you join the Best Choice Footwear Family we do our very best to earn yours.
            We care about your experience, we want you to come back time and time again and we want you to feel part of our community; because we definitely see you as the most important part of ours!
            We take great pride in striving for 100% customer satisfaction, join the Best Choice Footwear Family to find out what else we do differently.
            Our footwear is designed focused on fit and comfort, manufactured to last with superior materials and production methods. We make riding and country boots better.
            We have time for you. Our over the phone fitting service specialises in matching your requirements to the perfect size and style.</p>
    </div>
{% endif %}
    <div class="container">
        <div class="row mx_auto">
            {% for pro in products.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                <div class="card text-center" style="min-width:18rem;" >
                    <a href="{{pro.get_url}}"><img src="{{pro.image.url}}" alt="{{pro.name}}" height="200px;" width="200px;"></a>
                    <div class="card-body">
                        <h4>{{pro.name}}</h4>
                        <p>{{pro.price}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
            <hr>
            <div class="text-center">
              {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}

FWproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy;Best Choice pvt.ltd. All rights Reserved.</p>
</div>

FWproject/templates/header.html
{% load static %}
<header>
    <center>
       <a href="{% url 'FWapp:procat' %}"></a> <img src="{% static 'image/logo.png' %}" alt='logoimage' width="200px;">
    </center>
</header>

FWproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <a class="nav-link" href="{% url 'FWapp:procat' %}">Home</a>
        </li>
        <li class="nav-item dropdown  {% if 'FWapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'FWapp:procat' %}">Products</a></li>
              {% for i in links %}
            <li><a class="dropdown-item" href="{{i.get_url}}">{{i.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"  ><i class="fa fa-shopping-cart"></i>{{item_count}}</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:Search' %}"   method="get">
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

FWproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{{product.description|truncatewords:155}}
{% endblock %}

{% block title %}
     {% if category %}
       {{product.name}} - Best Choice Shop
     {% endif %}
{% endblock %}

{% block content %}
<div class="row pro_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'FWapp:procat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>
    </div>
<div class="container">
<br>
  <div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem;">
            <img src="{{product.image.url}}" alt="{{product.name}}" height="300px;" width="300px;">
        </div>
    </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6" >
            <div>
               <h1 class="pro_title">{{product.name}}</h1>
               <p>${{product.price}}</p>
               <p class="my_title">Product Description</p>
               <p class="text-justify pro_text">{{product.description}}</p>
               {% if product.stock <= 0 %}
               <p class="text-justify pro_text"><b>Out of Stock</b></p>
               {% else %}
               <a class="btn btn-secondary" href="{% url 'cart:add_to_cart' product.id %}">Add to Cart</a>
               {% endif %}
            </div>
        </div>
    </div>
  </div>
</div>
{% endblock %}

FWproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        We have variety of products.
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div class="row search_row_class">
    <p class="text-center search_text">You have searched for:<b>"{{query}}"</b></p>
</div>
<div class="container">
        <div class="row mx_auto">
            {% for pro in products %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                <div class="card text-center" style="min-width:18rem;" >
                    <a href="{{pro.get_url}}"><img src="{{pro.image.url}}" alt="{{pro.name}}" height="200px;" width="200px;"></a>
                    <div class="card-body">
                        <h4>{{pro.name}}</h4>
                        <p>{{pro.price}}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center search_text"> No results found</p>
            </div>
            {% endfor %}
        </div>
</div>
{% endblock %}